### ISSUE TITLE
Alpha-0.0.1 To-do

### ISSUE THREAD

**Issue by Mozirilla** [Mozirilla/order-up#1]
# Create Assets
- [ ] Start mod package structure and JAR files
- [ ] Create required assets folder structure

### Order Counter
- [ ] Create model and texture of initial `Order Counter`
- [ ] Create basic order counter GUI textures
- [ ] Create basic order counter GUI with buttons, item slots, etc.
- [ ] Create initial Java code for `Order Counter`

### Bill Board
- [ ] Create model and texture of initial `Billboard`
- [ ] Create initial Java code for `Billboard`
- [ ] Research `Flier` "slots" without GUI on Billboard

#### Fliers
- [ ] Create model and texture of initial `Flier`
- [ ] Create entity/item of initial `Flier`

#### Business Licenses
- [ ] Create model and texture of initial `Business License`
- [ ] Create entity/item of initial `Business License`

#### Franchise SOP
- [ ] Research Patchouli and Modonomicon
- [ ] Create model and texture of initial `Franchise SOP`
- [ ] Create entity/item of initial `Franchise SOP`
